version: '3.8'

services:
  redpanda-0:
    image: redpandadata/redpanda:v24.1.21
    command:
    - redpanda start
    - --smp 1
    - --memory 1G
    - --reserve-memory 0M
    - --overprovisioned
    - --node-id 0
    - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr PLAINTEXT://redpanda-0:29092,OUTSIDE://localhost:9092
    - --pandaproxy-addr PLAINTEXT://0.0.0.0:8082
    - --advertise-pandaproxy-addr PLAINTEXT://redpanda-0:8082
    - --rpc-addr 0.0.0.0:33145
    - --advertise-rpc-addr redpanda-0:33145
    ports:
    - "9092:9092"
    - "8082:8082"

  redpanda-1:
    image: redpandadata/redpanda:v24.1.21
    command:
    - redpanda
    - start
    - --smp 1
    - --memory 1G
    - --reserve-memory 0M
    - --overprovisioned
    - --node-id 1
    - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9093
    - --advertise-kafka-addr PLAINTEXT://redpanda-1:29092,OUTSIDE://localhost:9093
    - --pandaproxy-addr PLAINTEXT://0.0.0.0:8082
    - --advertise-pandaproxy-addr PLAINTEXT://redpanda-1:8082
    - --rpc-addr 0.0.0.0:33145
    - --advertise-rpc-addr redpanda-0:33145
    - --seeds redpanda-0:33145
    ports: ["9093:9093"]

  redpanda-2:
    image: redpandadata/redpanda:v24.1.21
    command:
    - redpanda
    - start
    - --smp 1
    - --memory 1G
    - --reserve-memory 0M
    - --overprovisioned
    - --node-id 2
    - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9094
    - --advertise-kafka-addr PLAINTEXT://redpanda-2:29092,OUTSIDE://localhost:9094
    - --pandaproxy-addr PLAINTEXT://0.0.0.0:8082
    - --advertise-pandaproxy-addr PLAINTEXT://redpanda-2:8082
    - --rpc-addr 0.0.0.0:33145
    - --advertise-rpc-addr redpanda-0:33145
    - --seeds redpanda-0:33145
    ports: ["9094:9094"]

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: gameingestor
      POSTGRES_PASSWORD: darksecret
      POSTGRES_DB: gameingestordb
    ports: ["5432:5432"]
    volumes: [postgres-data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gameingestor -d gamedb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: